name: Sync Pull Request
on:
  pull_request_target:
    types: [labeled]

jobs:
  sync_pull_request:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'sync')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Sync with master
        run: |
          set -x
          git remote add pr_remote ${{ github.event.pull_request.head.repo.html_url }}
          git fetch pr_remote ${{ github.event.pull_request.head.ref }}
          git checkout pr_remote/${{ github.event.pull_request.head.ref }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/master
          echo git push pr_remote HEAD:${{ github.event.pull_request.head.ref }}
      - name: Remove label
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X "DELETE" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/sync
